name: Health Check

on: push

jobs:
  health-check:
    name: Health Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Packages
        run: npm install

      - name: Check linting
        run: npm run lint

      - name: Run unit tests
        run: npm run test
